### PR TITLE
Fixing Calling of sysargs with argparser

### PR DESCRIPTION
**Pull request by shivammehta25**
Refractored the Code and arg parser to parse input arguments

### CODE REVIEW

**Comment by pradeepjairamani** [comment]
Hello,

Thanks for your contribution, PR merged.

Best Regards

**Comment by pradeepjairamani** [comment]
I have also made a few changes, please check them for future references :)

https://github.com/pradeepjairamani/nmappy/blob/f680c96aa67ecd0d03dd74a9af995cc2e84bfeac/nmappy.py#L72
&

https://github.com/pradeepjairamani/nmappy/blob/f680c96aa67ecd0d03dd74a9af995cc2e84bfeac/nmappy.py#L44

Best Regards

**Comment by shivammehta25** [comment]
you don't need -h arg parser by default give you -h :)

Regards,
Shivam Mehta
www.shivammehta.me

On Tue, Apr 17, 2018 at 6:33 PM, Pradeep Jairamani <notifications@github.com

**Comment by pradeepjairamani** [comment]
It was for showing the help menu when no option is provided by the user ;)

Best Regards

**Pull request merged**
